version: 2
jobs:
  test:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/aedipamoss/stationery
    steps:
    - checkout
    - run:
        command: make test
  lint:
    docker:
    - image: circleci/golang:1.10
      environment:
        CGO_ENABLED: 0
    working_directory: /go/src/github.com/aedipamoss/stationery
    steps:
    - checkout
    - run: go get -u github.com/alecthomas/gometalinter
    - run: gometalinter --install
    - run: gometalinter --deadline 60s --vendor ./...
workflows:
  version: 2
  ci:
    jobs:
      - test
      - lint
